config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :items, only: [:index,:show]

  resources :merchants, only: [:index]

  resources :users, only: [:new, :edit]

  resources :carts, only: [:create, :edit]


  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  get '/logout', to: "sessions#destroy"

  get '/profile', to: "users#show"
  post "/profile", to: "users#create"
  patch "/profile", to: "users#update"

  namespace :profile do
    resources :orders, only: [:index, :show, :update, :create]
  end

  namespace :dashboard do
    resources :items, only: [:index, :new, :update, :destroy, :create, :edit] do
      member { patch :activate }
      member { patch :deactivate }
    end
    resources :orders, only: [:show, :update, :edit]
    resources :coupons, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
      member {patch :activate}
      member {patch :deactivate}
    end
  end

  get '/cart', to: "carts#show"
  delete '/cart', to: "carts#destroy"
  patch '/cart', to: "carts#update"
  patch '/discount/cart', to: "carts#discount"

  get '/dashboard', to: "merchants#show"

  namespace :admin do
    get '/dashboard', to: 'admins#show'
    resources :users, only: [:index, :show, :update]
    resources :orders, only: [:update]
    resources :merchants, only: [:show, :index] do
      member {patch :activate}
      member {patch :deactivate}
      member {patch :downgrade}
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/views/welcome/index.html.erb
<div class="welcome">
  <h1>Welcome to Little Shop of Whiskeys!</h1>
  <div class="welcome-container">
    <div class="about-site">
      <div class="welcome-image">
        <img src="https://qph.fs.quoracdn.net/main-qimg-1435d61161f83638566e79e3f997f569" alt="picture of a whiskey glass">
      </div>
      <p>If you're a connoisseur of all things whiskey, this is the website for you! You can browse our various wares from Irish whiskey to Scotch whisky.</p>
    </div>

    <div class="welcome-login">
      <% if current_user %>
      <h3>Welcome, <%= current_user.name %></h3>
        <% if current_admin? %>
          <%= link_to "Dashboard", admin_dashboard_path, :class=>"browse-button" %>
        <% elsif current_merchant? %>
          <%= link_to "My Items", dashboard_items_path, :class=>"browse-button" %>
          <%= link_to "Dashboard", dashboard_path, :class=>"browse-button" %>
        <% elsif current_user? %>
          <%= link_to "My Orders", profile_orders_path, class: "browse-button" %>
        <% end %>
      <%= link_to "Log Out", logout_path, id: "button" %>
      <% else %>
      <h3>Log In</h3>
      <%= form_tag login_path do %>
      <%= label_tag :email_address %>
      <%= email_field_tag :email_address %>
      <br>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <br>
      <%= submit_tag "Log Me In", id: "medium-button" %>
      <% end %>
      <br>
      <br>
      <%= link_to "Not a Member? Register Here", new_user_path, id: "medium-button" %>
      <% end %>
    </div>

    <div class="welcome-nav-section">
      <h3>Browse</h3>
      <%= link_to "All Items", items_path, class: "browse-button" %>
      <%= link_to "All Merchants", merchants_path, class: "browse-button" %>
    </div>

    <div class="about-us">
      <h3>About Creators</h3>
      <div class="about-us-blurb">
        <p>This project was part of our second Module at Turing School of Software & Design. The goal of our website was to create a working shop where users can register, create orders, browse wares, or become merchants. Our focus was on logical namespacing as well as dividing up tasks among the Models, Views, and Controllers.</p>
      </div>
      <div class="about-us-links">
        <%= link_to "Jeremy Bennett's Github", "https://github.com/JaxJafinPapau" %>
        <br>
        <%= link_to "Ethan Grab's Github", "https://github.com/Stoovles" %>
        <br>
        <%= link_to "Carrie Walsh's Github", "https://github.com/carriewalsh" %>
        <br>
        <%= link_to "Matt Weiss's Github", "https://github.com/Matt-Weiss" %>
      </div>
    </div>
  </div>
</div>