config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :items, only: [:index,:show]

  resources :merchants, only: [:index]

  resources :users, only: [:new, :edit]

  resources :carts, only: [:create, :edit]


  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  get '/logout', to: "sessions#destroy"

  get '/profile', to: "users#show"
  post "/profile", to: "users#create"
  patch "/profile", to: "users#update"

  namespace :profile do
    resources :orders, only: [:index, :show, :update, :create]
  end

  namespace :dashboard do
    resources :items, only: [:index, :new, :update, :destroy, :create, :edit] do
      member { patch :activate }
      member { patch :deactivate }
    end
    resources :orders, only: [:show, :update, :edit]
    resources :coupons, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
      member {patch :activate}
      member {patch :deactivate}
    end
  end

  get '/cart', to: "carts#show"
  delete '/cart', to: "carts#destroy"
  patch '/cart', to: "carts#update"
  patch '/discount/cart', to: "carts#discount"

  get '/dashboard', to: "merchants#show"

  namespace :admin do
    get '/dashboard', to: 'admins#show'
    resources :users, only: [:index, :show, :update]
    resources :orders, only: [:update]
    resources :merchants, only: [:show, :index] do
      member {patch :activate}
      member {patch :deactivate}
      member {patch :downgrade}
    end
  end


end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < ApplicationController
  before_action :require_admin

  def show
    if User.find(params[:id]).role == "user"
      redirect_to admin_user_path(User.find(params[:id]))
    else
      @merchant = User.find(params[:id])
      @orders = @merchant.merchant_pending_orders
      @popular_five = @merchant.items.popular_five
      @top_3_states = User.top_three_states(@merchant)
    end
  end

  def index
    @merchants = User.where(role: 1).order(:name)
  end

  def deactivate
    @merchant = User.find(params[:id])
    @merchant.update(enabled: false)
    redirect_to admin_merchants_path,  danger: "Merchant #{@merchant.id} has been disabled"
  end

  def activate
    @merchant = User.find(params[:id])
    @merchant.update(enabled: true)
    redirect_to admin_merchants_path, success: "Merchant #{@merchant.id} has been enabled"
  end

  def downgrade
    @merchant = User.find(params[:id])
    @merchant.items.each do |item|
      item.update(enabled: false)
    end
    @merchant.update(role: 'user')
    redirect_to admin_user_path(@merchant), success: "Merchant #{@merchant.id} has been downgraded to a user"
  end

  private

    def require_admin
      render file: "/public/404" unless current_admin?
    end


end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
before_action :require_merchant
skip_before_action :require_merchant, only: [:index]
  def index
    @merchants = User.active_merchant
    @top = User.top_three_merchants_overall
    @fastest = User.three_fastest
    @slowest = User.three_slowest
    @states = User.top_three_states_overall
    @citystates = User.top_three_city_states_overall
    @orders = User.three_biggest_orders
    @total_revenue = User.total_sales_array
    @top_three = User.top_merchants_array
    @biggest = User.biggest_orders_array
    @fastest_array = User.fastest_array
    @slowest_array = User.slowest_array
    @overall_states = User.states_overall_array
    @overall_cities = User.cities_overall_array
  end

  def show
    @merchant = User.find(current_user.id)
    @items = Item.merchant_items(current_user)
    @orders = @merchant.merchant_pending_orders
    @popular_five = @items.popular_five
    @top_3_states = User.top_three_states(@merchant)
    @top_3_cities = User.top_three_city_states(@merchant)
    @top_user = User.top_user_by_orders(@merchant)
    @top_user_by_items = User.top_user_by_items(@merchant)
    @top_users_by_revenue = User.top_users_by_revenue(@merchant)

    @monthly_revenue = @merchant.monthly_revenue_array
    @daily_revenue = @merchant.daily_revenue_array
    @percent = @merchant.percent_inventory_array
    @three_states_array = User.top_three_states_array(@merchant)
    @three_cities_array = User.top_three_city_states_array(@merchant)
  end

  private

  def require_merchant
    render file: "/public/404" unless current_merchant?
  end

end

app/views/merchants/index.html.erb
<div class="merch-stats">
 <h2> Statistics </h2>
  <div class="top-merchants">
    <h5>Merchant Chart:</h5>
    <%= pie_chart @total_revenue %>
    <br>
    <h5>Top 3 Merchants:</h5>
    <%= pie_chart @top_three %>
    <br>
    <h5>Biggest Orders:</h5>
    <%= pie_chart @biggest %>
  <% @orders.each do |order| %>
  ID: <%= order.id %> -
  <%= order.sum %> units<br>
  <% end %><br>
  </div>

  <div class="merchant-speed">
  <h5>Fastest Merchants:</h5>
  <%= bar_chart @fastest_array %>
  <% @fastest.each do |merchant| %>
      <%= merchant.name %> -
      <%= merchant.avg %><br>
    <% end %><br>
  <h5>Slowest Merchants:</h5>
    <%= bar_chart @slowest_array %>
  <% @slowest.each do |merchant| %>
      <%= merchant.name %> -
      <%= merchant.avg %><br>
    <% end %><br>
  </div>

  <div class="top-geographical">
  <h5>Top 3 States:</h5>
  <p id="pie-chart"><%= pie_chart @overall_states %></p>
    <% @states.each do |relation| %>
    <%= relation.state %> -
    <%= relation.count %> orders<br>
  <% end %><br>
  <h5>Top 3 Cities:</h5>
  <p id="pie-chart"><%= pie_chart @overall_cities %></p>
  <% @citystates.each do |relation| %>
    <%= relation.citystate %> -
    <%= relation.count %> orders<br>
  <% end %><br>
  </div>
</div>

<div class="merchants-container">
  <% @merchants.each do |merchant| %>
  <div class="merchant-card">
    <h2><%= merchant.name %></h2>
    <p>Ships from: <%= merchant.city %>, <%= merchant.state %></p>
    <p>Member since: <%= merchant.created_at.to_date %>
    </div>
    <% end %>
</div>

app/views/merchants/show.html.erb
<% if current_user %>

<section class="statistics">
  <h2>Statistics</h2>
  <% if @popular_five %>
  <div class="five_most">
    <h3>Most Popular Items</h3>
    <% @popular_five.each do |item| %>
    <div class="popular">
      <a><img src=<%= item.image_url %> class="tiny-image" alt="image of <%= item.item_name %>"></a>
      <%= item.item_name %> -
      <%= item.quantity_sold %> bought
    </div>
    <% end %>
    <div class="percentage-sold">
      Total Items Sold: <%= current_user.total_quantity_sold %>
      <br>
      Percentage of Inventory Sold: <%= current_user.percentage_sold.round(2) %>%
      <p id="pie-chart"><%= pie_chart @percent %></p>
      Revenue per Month -
      <p id="bar-chart"><%= bar_chart @monthly_revenue %></p>
      Revenue per Day of the Month - 
      <p id="bar-chart"><%= bar_chart @daily_revenue %></p>
    </div>
    <br>

    <div class="charts">
      - Top 3 States   -------------------------------   Top 3 Cities -
    </div>
    <div class="charts">
      <p id="pie-chart"><%= pie_chart @three_states_array %></p>
      <p id="pie-chart"><%= pie_chart @three_cities_array %></p>
    </div>
  </div>
  <% end %>
  <div>
  <h3>Top Customers</h3>
  <% if @top_user %>
      Top Customer (orders): <%= @top_user.name %> - <%= @top_user.count %><br>
      Top Customer (items): <%= @top_user_by_items.name %> - <%= @top_user_by_items.sum %><br>
      Top Customers (revenue):<% @top_users_by_revenue.each do |customer| %><br>
        <%= customer.name %> - <%= number_to_currency(customer.sum) %>
      <% end %>
  <% end %>
  </div>

</section>


<br>

  <div class='order-card'>
    <h3>Name: <%= current_user.name %></h3>
    <p>Street Address: <%= current_user.street_address %></p>
    <p>City: <%= current_user.city %></p>
    <p>State: <%= current_user.state %></p>
    <p>Zip Code: <%= current_user.zip_code %></p>
    <p>Email Address: <%= current_user.email_address %></p>
    <%= link_to "My Items", dashboard_items_path, id: "button" %>
    <%= link_to "My Coupons", dashboard_coupons_path, id: "button" %>
  </div>

  <div class='pending-orders'>
    <% @orders.each do |order| %>
    <div class="order-card">
      <h3><%= link_to "Order ID: #{order.id}", dashboard_order_path(order) %></h3>
      <p>Ordered On: <%= order.created_at %></p>
      <p>Quantity: <%= @merchant.my_item_count(order) %></p>
      <p>Total Price: <%= @merchant.my_total(order) %></p>
    </div>
    <% end %>
  </div>


<% else redirect_to "/public/404" %>
<% end %>