config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :items, only: [:index,:show]

  resources :merchants, only: [:index]

  resources :users, only: [:new, :edit]

  resources :carts, only: [:create, :edit]


  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  get '/logout', to: "sessions#destroy"

  get '/profile', to: "users#show"
  post "/profile", to: "users#create"
  patch "/profile", to: "users#update"

  namespace :profile do
    resources :orders, only: [:index, :show, :update, :create]
  end

  namespace :dashboard do
    resources :items, only: [:index, :new, :update, :destroy, :create, :edit] do
      member { patch :activate }
      member { patch :deactivate }
    end
    resources :orders, only: [:show, :update, :edit]
    resources :coupons, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
      member {patch :activate}
      member {patch :deactivate}
    end
  end

  get '/cart', to: "carts#show"
  delete '/cart', to: "carts#destroy"
  patch '/cart', to: "carts#update"
  patch '/discount/cart', to: "carts#discount"

  get '/dashboard', to: "merchants#show"

  namespace :admin do
    get '/dashboard', to: 'admins#show'
    resources :users, only: [:index, :show, :update]
    resources :orders, only: [:update]
    resources :merchants, only: [:show, :index] do
      member {patch :activate}
      member {patch :deactivate}
      member {patch :downgrade}
    end
  end


end

app/models/cart.rb
class Cart
  attr_reader :contents


  def initialize(contents)
    @contents = contents || Hash.new(0)
    @contents.default = 0
  end

  def items
    Item.where(id: @contents.keys)
  end

  def total_count
    @contents.values.sum if @contents
  end

  def count_of(item_id)
    @contents[item_id.to_s]
  end

  def add_item(item_id)
    @contents[item_id.to_s] += 1
  end

  def subtotal(item)
    @contents[item.id.to_s] * item.current_price
  end

  def cart_total
    items.inject(0) do |total, item|
      total += subtotal(item)
    end
  end

  def regular_items(coupon)
    items.where.not(id: coupon.item_list)
  end

  def discount_items(coupon)
    items.where(id: coupon.item_list)
  end

  def discount_total(coupon)
    regular_total = regular_items(coupon).inject(0) {|total, item| total += subtotal(item)}
    if coupon.discount == "dollar"
      if (cart_total - regular_total - coupon.amount) < 0
        regular_total
      else
        cart_total - coupon.amount
      end
    elsif coupon.discount == "percent"
      if coupon.amount < 100
        discount_total = discount_items(coupon).inject(0) {|total, item| total += subtotal(item)*(coupon.percent_off)}
      else
        discount_total = 0
      end
      discount_total + regular_total
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :require_visitor_or_user
  def show
    ids = @cart.contents.keys
    @coupon = Coupon.find_by(name: session[:coupon])
  end

  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    session[:cart] = @cart.contents
    redirect_to items_path, info: "You now have #{session[:cart][item.id.to_s]} #{item.item_name} in your cart."
  end

  def destroy
    session.delete(:cart)
    redirect_to cart_path
  end

  def update
    if params[:update] == "remove" || params[:quantity] == "0"
      session[:cart].delete(params[:item_id])
    else
      session[:cart][params[:item_id]] = params[:quantity].to_i
    end
    if @cart.contents.first == nil
      destroy
    else
      redirect_to cart_path
    end
  end

  def discount
    if current_user.my_used_coupons?(coupon_params)
      @coupon = Coupon.find_by(name: session[:coupon])
      flash.now[:danger] = "Coupon has already been used"
      render :show
    elsif Coupon.where(name: coupon_params, active: "deactivated").first
      @coupon = Coupon.find_by(name: session[:coupon])
      flash.now[:danger] = "Coupon does not exist"
      render :show
    elsif Coupon.where(name: coupon_params).pluck(:name).include?(coupon_params)
      session[:coupon] = coupon_params
      @coupon = Coupon.find_by(name: coupon_params)
      flash.now[:info] = "#{coupon_params} has been added"
      render :show
    else
      @coupon = Coupon.find_by(name: session[:coupon])
      flash.now[:danger] = "Coupon does not exist"
      render :show
    end
  end

private
  def require_visitor_or_user
    render file: "/public/404" unless current_user? || !current_user
  end

  def coupon_params
    if params["Coupon code"] != ""
      params.require("Coupon code")
    else
      session[:coupon]
    end
  end
end

app/views/carts/show.html.erb
<h3 class="heading">My Cart:</h3>
<div class="cart-container">
  <% if @cart.items.first %>
    <% @cart.items.each do |item| %>
      <div class="cart-card">
        <h3><%= item.item_name %></h3>
        <div class="image-container">
          <img src="<%= item.image_url%>" alt="image of <%= item.item_name %>" class="small-image">
        </div>
        <div class="cart-item-info">
          Merchant: <%= item.merchant_name %>
          <br>
          Current Price: <%= number_to_currency(item.current_price) %>
          <br>
          Quantity: <%= @cart.contents[item.id.to_s] %>
          <%= form_tag(cart_path(item_id: item.id), method: :patch) do %>
          <%= select_tag :quantity, options_for_select(0..item.inventory), selected: @cart.contents[item.id.to_s] %>
          <br>
          <br>
          <%= submit_tag 'Update Quantity', id: :button %>
          <br>
          <% end %>
        </div>
        <div class="total">
          <h4>Subtotal: <%= number_to_currency(@cart.subtotal(item)) %></h4>
          <%= link_to 'Remove Item', cart_path(update: :remove, item_id: item.id),  method: :patch, id: :button %>
        </div>
      </div>
    <% end %>
    <div class="cart-card">
      <div class="total">
        Total: <%= number_to_currency(@cart.cart_total) %>
        <% if session[:coupon] %>
          <div id="discount">
            Discount Total: <%= number_to_currency(@cart.discount_total(@coupon)) %>
          </div>
        <% end %>
      <% if !current_user %>
      <div class="login-register">
        Please <%= link_to 'Register', new_user_path, id: "button" %> or <%= link_to 'Log In', login_path, id: "button" %> to place your order.
      </div>
      <% else %>
      <div class="checkout">
        <%= button_to 'Check Out', profile_orders_path, method: :create, class: "browse-button" %>
        <%= form_tag(discount_cart_path, method: :patch) do %>
          <%= text_field_tag "Coupon code" %>
          <%= submit_tag "Add Coupon" %>
        <% end %>
      </div>
      <% end %>
    </div>
    </div>
  <%= link_to 'Empty my cart', cart_path, method: :delete, id: "button" %>
<% else %>
  <div>Your Cart is empty!</div>
<% end %>
</div>